Update route_match.php
"routeHandler" does not exist
com.caucho.quercus.QuercusErrorException: Call to undefined function routeHandler 
com.caucho.quercus.QuercusErrorException: Call to undefined function routeHandler 

in the java api its "requestHandler"

I have checked this and it works